### ISSUE TITLE
Struve and related functions?

### ISSUE THREAD

**Issue by heltonmc** [gwater/Struve.jl#11]
I'm wondering what your thoughts are on including the 'related functions' to Struve functions here? 

On NIST chapter 11 (https://dlmf.nist.gov/11) it is Struve and related functions. These might include
- Struve functions
- Lommel
- Anger
- Weber
- Anger-Weber
- Kelvin (compute with imaginary bessel functions)
- Scorer (might be best with Airy functions)

I do not have implementations ready for these yet to contribute, but would like to define the scope of this package. I would really like to build up the special function libraries in Julia and would think this would be a nice companion to Bessels.jl that I can link to from there!

**Comment by gwater** [comment]
Hmm, good question. I am asking myself a few questions when I think about scope: Could these functions benefit from sharing code (developer side)? Would users often use these functions side by side (user side)?

**Comment by heltonmc** [comment]
Yes - good questions! 

Of course, these functions are rarely used so on the user side it would be hard for me to say but they are related with some code overlap. Looking at https://arxiv.org/pdf/2104.01700.pdf, Lommel, Anger-Weber, and Struve functions all share similar asymptotic expansions and the forms of the power series would be very similar. Of course these are all closely related to Bessel functions but I think these are better as a separate package as they are less used.

For developing, I'm not sure if these functions really require a different package if there is going to be any code overlap. I'd imagine even including all of these functions will be pretty lightweight. Though, would it be harder for users to find say Anger functions if they were under a package called `Struve.jl`?

I think my last point may be mute. There is some momentum to having `SpecialFunctions.jl` reexport native julia implementations so we can include a list of Special function libraries there which would help users identify which packages they need to use. Therefore, we can point them here for struve, lommel, anger, kelvin etc. But I do think defining a very specific scope for this package would be nice! `SpecialFunctions.jl` seems to struggle about not having a scope so noone knows what to include there.

I might suggest that this package includes
- Struve Functions
- Lommel
- Anger
- Weber
- Anger-Weber

Scorer functions could go in a separate package alongside airy functions. That kind of leaves Kelvin functions out on their own but they are so closely related to bessel functions it might be good to have them there (can have that discussion over at `Bessels.jl`).... 

Edit: And of course including more functions here increases maintenance burden for you for a package that you may have wanted to be small. I'm of course happy to help maintain as well.
