### ISSUE TITLE
Bug for x=0

### ISSUE THREAD

**Issue by Veenty** [gwater/Struve.jl#14]
When trying

Struve.H(0,z) I get the error

```DomainError with 0.9999999999999964:
integrand produced NaN in the interval (0.9999999999999929, 1.0)
Stacktrace:
  [1] evalrule(f::QuadGK.var"#14#23"{Struve.var"#3#4"{Float64, Int64, Float64}, Float64, Float64}, a::Float64, b::Float64, x::Vector{Float64}, w::Vector{Float64}, gw::Vector{Float64}, nrm::typeof(norm))
    @ QuadGK ~/.julia/packages/QuadGK/XqIlh/src/evalrule.jl:37
  [2] adapt(f::QuadGK.var"#14#23"{Struve.var"#3#4"{Float64, Int64, Float64}, Float64, Float64}, segs::Vector{QuadGK.Segment{Float64, Float64, Float64}}, I::Float64, E::Float64, numevals::Int64, x::Vector{Float64}, w::Vector{Float64}, gw::Vector{Float64}, n::Int64, atol::Float64, rtol::Float64, maxevals::Int64, nrm::typeof(norm))
    @ QuadGK ~/.julia/packages/QuadGK/XqIlh/src/adapt.jl:48
  [3] do_quadgk(f::QuadGK.var"#14#23"{Struve.var"#3#4"{Float64, Int64, Float64}, Float64, Float64}, s::Tuple{Float64, Float64}, n::Int64, atol::Nothing, rtol::Nothing, maxevals::Int64, nrm::typeof(norm), segbuf::Nothing)
    @ QuadGK ~/.julia/packages/QuadGK/XqIlh/src/adapt.jl:37
  [4] #46
    @ ~/.julia/packages/QuadGK/XqIlh/src/adapt.jl:219 [inlined]
  [5] handle_infinities(workfunc::QuadGK.var"#46#47"{Nothing, Nothing, Int64, Int64, typeof(norm), Nothing}, f::Struve.var"#3#4"{Float64, Int64, Float64}, s::Tuple{Float64, Float64})
    @ QuadGK ~/.julia/packages/QuadGK/XqIlh/src/adapt.jl:110
  [6] #quadgk#45
    @ ~/.julia/packages/QuadGK/XqIlh/src/adapt.jl:218 [inlined]
  [7] quadgk
    @ ~/.julia/packages/QuadGK/XqIlh/src/adapt.jl:216 [inlined]
  [8] integrate
    @ ~/.julia/packages/Struve/BgIsA/src/integral.jl:5 [inlined]
  [9] _K_integral(ν::Int64, z::Float64)
    @ Struve ~/.julia/packages/Struve/BgIsA/src/integral.jl:13
 [10] _H_integral(ν::Int64, z::Float64)
    @ Struve ~/.julia/packages/Struve/BgIsA/src/integral.jl:17
 [11] Laplace2D(ξ::Vector{Float64}, R::Int64)
    @ Main ~/Documents/Julia_develop/InterpFourierChebyshev/src/KernelsFourier.jl:15
 [12] top-level scope
    @ ~/Documents/Julia_develop/InterpFourierChebyshev/src/KernelsFourier.jl:30
```

**Comment by heltonmc** [comment]
What is ‘z’ in this case?

**Comment by Veenty** [comment]
Ups sorry, that z should be x.
Basically I'm seeing errors for Struve.H(0,0.) and Struve.H(1,0.)

**Comment by heltonmc** [comment]
Looks like problem stems from
```julia
julia> Struve._K0_integral(0.0)
ERROR: DomainError with 0.875:
integrand produced NaN in the interval (0.75, 1.0)
```

The issue is that the integral form for Struve_k (https://dlmf.nist.gov/11.5#E2) is only defined for z > 0

Though for this case I would recommend using `struveh`..
```julia
julia> Struve.struveh(0.0, 0.0)
0.0

julia> Struve.struveh(0.0, 0.0)
0.0

julia> Struve.struveh(1.0, 0.0)
0.0

julia> Struve.struveh(1.0, 0.1)
0.0021206516014255546
```

**Comment by Veenty** [comment]
What is the difference between Struve.H and Struve.struveh? And how do I choose between the 2?

**Comment by heltonmc** [comment]
They compute the same function. Struve.H will always compute the struve function using the integral form solved with adaptive gauss quadrature integration. This approach will be very slow.

`Struve.struveh` uses more optimized methods to compute the function though they are only for real arguments but will fall back to Struve.H when necessary. So it's probably always recommended to use struveh as that will give you fast branches (without allocating) and fall back to gauss quadrature if needed. Unfortunately, I haven't had time to complete #13 as that would avoid any fallbacks to gauss quadrature.... so always use struveh unless you have a good reason to prefer the integral form.

**Comment by gwater** [comment]
I dont really see why 
```julia
integrate(t -> 1/sqrt(1 + t^2), 0.0, Inf)
```
is producing this error. The integrand appears well-defined on the domain of integration

**Comment by gwater** [comment]
I think this is happening because QuadGK is rewriting the integrand internally to make the integral proper (remove the infinite boundary).

**Comment by gwater** [comment]
So basically, the current implementation would have to calculate the difference between two infinities at x=0 to get the correct result. I guess we could implement a special case… But since the value of Struve functions at 0 is quite well known im not very motivated to address this, to be quite honest.

**Comment by heltonmc** [comment]
Ya I was thinking that ‘struveh’ was the default user function and it just falls back to integral form when no special branches exist.

One case this probably fails as well is for complex zero. We could simply define Struveh for complex arguments to use power series for |z|<1 as a sort of hack around this. The power series will work in complex plane. And just always recommend struveh to be used.

**Comment by gwater** [comment]
further efforts should focus on extending Bessels.jl

see discussion in https://github.com/gwater/Struve.jl/pull/13
