### ISSUE TITLE
Thoughts on updating this package?

### ISSUE THREAD

**Issue by heltonmc** [gwater/Struve.jl#9]
Hi there @gwater !! Thanks for contributing this package. I came across this while thinking about bringing together native Julia implementations of special functions and this caught my interest due to the overlap with other functions.

I was wondering how you felt about updating this package or if you are still interested in developing some of these functions? I read through the code base and noticed there are a couple of places where it might be possible to make some optimizations. In general, I would be open to contributing some PRs for this. Would that be ok?

I don't want to change too much if you are happy with this so let me know.

Some of the changes I have in mind would be to - (1) update and optimize all the power series forms so that they can be run to a desired tolerance (and be much faster), (2) not rely on QuadGK or any integration tools that require allocation, (3) use some of the relations to bessel function (Bessels.jl) to give some of the identities.

Let me know your general thoughts on the future of this package and where you would want to see it go!!
-Michael

**Comment by gwater** [comment]
Hi @heltonmc , thanks for your patience.

I think implementing these functions properly (i.e. using some nice polynomials) would be a very worthwhile goal. I'm a bit hesitant w.r.t. to root-finding approaches just because performance would depend strongly on the implementation. But I know that root-finding is an established approach to special functions.

I would absolutely be open to PRs and getting the package in shape for the General registry!

**Comment by gwater** [comment]
I have also noted some links which could be used to validate new implementations, in #1 #2 and #3

**Comment by heltonmc** [comment]
No worries!

In regards to the polynomials we can absolutely use that for the 0 and 1 orders if we want. We have had a lot of success in using these for bessel functions, however, they do take some time to get right to give the full 15-16 digits of accuracy.

For testing we can just use the power series in arbitrary precision. I've gone through and manually tested that against mathematica and they match exactly. That will be much faster than using quadgk to test for sure.

I don't plan on using any root finding techniques. Really just developing highly optimized versions of power series, large argument expansions, and large order expansions. And if needed filling the rest of the regions with recurrence. This will be about an order of magnitude faster than using adaptive numerical integration for this. However, it might be adequate to also consider fixed point gauss quadrature for this...

**Comment by gwater** [comment]
Yeah, sounds good. Going by the [dlmf advice](https://dlmf.nist.gov/11.13#iii)  a fixed point (rather than adaptive) quadrature sounds most promising to me

**Comment by heltonmc** [comment]
Yes - ideally though we could have a tight bound on the order because we will need a variable amount of points depending on if the order is too high. I still think the best method is to also employ the asymptotic expansion for large orders. The integral forms are typically much faster converging for small orders
